### ISSUE TITLE
wavelet analysis is crashing the GUI

### ISSUE THREAD

**Issue by feyzanar** [tensionhead/pyBOAT#24]
Hello! 

I am using the pyBOAT GUI for the first time and want to run the wavelet analysis. It gives an error related to setting the rotation for the color bar label in the plot and crashes. Is there anything I can do to fix this?

'''
UserWarning: Adding colorbar to a different Figure <Figure size 640x480 with 3 Axes> than <Figure size 640x480 with 0 Axes> which fig.colorbar is called on.
  cb = ppl.colorbar(
Traceback (most recent call last):
  File "/Users/fnarslan/miniconda3/envs/pyboat/lib/python3.12/site-packages/pyboat/ui/data_viewer.py", line 968, in run_wavelet_ana
    self.anaWindows[self.w_position] = WaveletAnalyzer(
                                       ^^^^^^^^^^^^^^^^
  File "/Users/fnarslan/miniconda3/envs/pyboat/lib/python3.12/site-packages/pyboat/ui/analysis.py", line 147, in __init__
    self.initUI(position)
  File "/Users/fnarslan/miniconda3/envs/pyboat/lib/python3.12/site-packages/pyboat/ui/analysis.py", line 167, in initUI
    pl.plot_signal_modulus(
  File "/Users/fnarslan/miniconda3/envs/pyboat/lib/python3.12/site-packages/pyboat/plotting.py", line 322, in plot_signal_modulus
    cb.set_label("Wavelet Power", rotation="0", labelpad=-12, fontsize=0.9 * label_size)
  File "/Users/fnarslan/miniconda3/envs/pyboat/lib/python3.12/site-packages/matplotlib/colorbar.py", line 967, in set_label
    self.ax.set_xlabel(label, loc=loc, **kwargs)
  File "/Users/fnarslan/miniconda3/envs/pyboat/lib/python3.12/site-packages/matplotlib/axes/_base.py", line 3562, in set_xlabel
    return self.xaxis.set_label_text(xlabel, fontdict, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fnarslan/miniconda3/envs/pyboat/lib/python3.12/site-packages/matplotlib/axis.py", line 1858, in set_label_text
    self.label.update(kwargs)
  File "/Users/fnarslan/miniconda3/envs/pyboat/lib/python3.12/site-packages/matplotlib/text.py", line 205, in update
    ret.extend(super().update(kwargs))
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fnarslan/miniconda3/envs/pyboat/lib/python3.12/site-packages/matplotlib/artist.py", line 1206, in update
    return self._update_props(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/fnarslan/miniconda3/envs/pyboat/lib/python3.12/site-packages/matplotlib/artist.py", line 1192, in _update_props
    ret.append(func(v))
               ^^^^^^^
  File "/Users/fnarslan/miniconda3/envs/pyboat/lib/python3.12/site-packages/matplotlib/text.py", line 1234, in set_rotation
    raise ValueError("rotation must be 'vertical', 'horizontal' or "
ValueError: rotation must be 'vertical', 'horizontal' or a number, not 0
zsh: abort      pyboat
'''

**Comment by tensionhead** [comment]
Hi @feyzanar, thx for reaching out! 
The error you reported I remembered fixing a while ago with d4128ba, are you sure you are running the latest pyBOAT 0.9.12?

**Comment by feyzanar** [comment]
Hi @tensionhead, You are right. I pip-installed 0.9.9 and did not notice a newer release. When I upgraded to 0.9.12, the issue was indeed solved. Thanks a lot for your quick reply!

**Comment by tensionhead** [comment]
Ok great, you're welcome!
